spring:
  application:
    name: JMind_AIAgent
  ai:
    deepseek:
      api-key: ${DEEP_SEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
    zhipuai:
      api-key: ${ZHI_PU_API_KEY}
      chat:
        options:
          model: glm4.6